FROM node:20-bookworm-slim AS builder
WORKDIR /app
COPY frontend-react/package*.json ./
RUN npm install
COPY frontend-react/ ./
ARG VITE_API_HOST
ENV VITE_API_HOST=$VITE_API_HOST
RUN npm run build

FROM node:20-bookworm-slim
RUN npm install -g serve
WORKDIR /app
COPY --from=builder /app/dist ./dist
EXPOSE 3001
CMD ["serve", "-s", "dist", "-l", "3001"]
